### ISSUE TITLE
Huh?

### ISSUE THREAD

**Issue by GamingWithMoni** [MagiCircles/BanGDream#203]
What is this? Is this an APK? Also, does anyone here know where you can download all the files, or are all the files here?

**Comment by LatidoReMe** [comment]
This is a repository for [Bandori.Party](), a fan-site based on the BanG Dream! franchise. With the code hosted here and [here](https://github.com/MagiCircles/BanGDream-Static), you can run a version of the site.

Bandori.Party is __NOT__ an APK, but as an open-source project, you can download any of the code for the website via this handy button
![example image of button](https://user-images.githubusercontent.com/30684769/56774680-a0061380-6778-11e9-89c0-1b39133804ae.png)
or you can view the "Raw" of a file and just copy-paste the text as needed instead.

This issue will now be closed since it was just a question, and it doesn't require any coding. If you have any more questions about what exactly this is, please try one of our [other forms of contact](https://bandori.party/about/#contact)!

Alternatively, if you're interested in running this code locally or contributing to the project, please check out the wiki for our framework, [MagiCircles](https://github.com/MagiCircles/MagiCircles/wiki).

Have a good day! ^o^7
